[package]
name = "daemonize-me"
version = "0.1.0"
authors = ["Matheus Xavier <mxavier@mail.cmdforge.com>"]
edition = "2018"
keywords = ["daemon", "library"]
license = "BSD-3-Clause"
license-file= ""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
nix = "0.17"